repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # keep-sorted start
      - id: check-added-large-files
        name: check-for-added-large-files
        args: ["--maxkb=10240"]
      - id: check-ast
        name: check-python-ast
      - id: check-builtin-literals
        name: check-builtin-type-constructor-use
      - id: check-case-conflict
        name: check-for-case-conflicts
      - id: check-docstring-first
        name: check-docstring-is-first
      - id: check-executables-have-shebangs
        name: check-that-executables-have-shebangs
      - id: check-illegal-windows-names
        name: check-illegal-windows-names
      - id: check-json
        name: check-json
      - id: check-merge-conflict
        name: check-for-merge-conflicts
        args: ["--assume-in-merge"]
      - id: check-shebang-scripts-are-executable
        name: check-that-scripts-with-shebangs-are-executable
      - id: check-symlinks
        name: check-for-broken-symlinks
      - id: check-toml
        name: check-toml
      - id: check-vcs-permalinks
        name: check-vcs-permalinks
      - id: check-xml
        name: check-xml
      - id: check-yaml
        name: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
        name: debug-statements-python
      - id: destroyed-symlinks
        name: detect-destroyed-symlinks
      - id: detect-aws-credentials
        name: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
        name: detect-private-key
      - id: double-quote-string-fixer
        name: fix-double-quoted-strings
      - id: end-of-file-fixer
        name: fix-end-of-files
        exclude: |
          (?x)^(
              .*\.lock$|
              .flox/env.json
          )$
      - id: file-contents-sorter
        name: file-contents-sorter
      - id: fix-byte-order-marker
        name: fix-utf-8-byte-order-marker
      - id: forbid-new-submodules
        name: forbid-new-submodules
      - id: forbid-submodules
        name: forbid-submodules
      - id: mixed-line-ending
        name: mixed-line-ending-crlf-for-powershell-files
        args: [--fix=crlf]
        files: \.(ps1|psm1|psd1|pwsh)$
      - id: mixed-line-ending
        name: mixed-line-ending-lf-for-other-files
        args: [--fix=lf]
        exclude: \.(ps1|psm1|psd1|pwsh)$
      - id: name-tests-test
        name: python-tests-naming
      - id: no-commit-to-branch
        name: dont-commit-to-branch
        stages: [manual] # https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
      - id: pretty-format-json
        name: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys, --indent=2]
        files: \.json$
        exclude: |
          (?x)^(
              .*\.lock$|
              flake\.lock
          )$
      - id: requirements-txt-fixer
        name: fix-requirements-txt
      - id: sort-simple-yaml
        name: sort-simple-yaml-files
      - id: trailing-whitespace
        name: trim-trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: \.md$
        # keep-sorted end

  # keep-sorted start
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff
        name: ruff
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        name: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        name: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        name: gitleaks
  - repo: https://github.com/google/keep-sorted
    rev: v0.7.1
    hooks:
      - id: keep-sorted
        name: keep-sorted
        exclude: |
          (?x)^(
              .*\.lock$|
              .envrc
          )$
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
        name: yamlfmt
        args: [--formatter, retain_line_breaks_single=true]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        name: markdownlint
        files: \.md$
  - repo: https://github.com/nixos/nixfmt
    rev: v1.2.0
    hooks:
      - id: nixfmt
        name: nixfmt
        files: \.nix$
  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black
        name: black
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 42.84.0
    hooks:
      - id: renovate-config-validator
        args: [--strict]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint
        name: actionlint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    # Workaround official https://github.com/koalaman/shellcheck-precommit hooks that requires container runtime.
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        name: shellcheck
        args: []
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.2
    hooks:
      - id: markdown-link-check
        name: markdown-link-check
        entry: markdown-link-check
        language: node
        types: [file]
        files: \.md$
        args: ["--quiet"]
# keep-sorted end
